query GetAllProductsDashboard($getAllProductInput: GetAllProductInput!) {
	getAllProducts(getAllProductInput: $getAllProductInput) {
		length
		products {
			categoryId
			id
			images
			name
			price
		}
	}
}

query GetProductById($getProductById: GetProductById!) {
	getProductById(getProductById: $getProductById) {
		categoryId
		description
		id
		images
		name
		price
		slug
	}
}