query GetUserProfile {
	getProfile {
		id
		isAdmin
	}
}

mutation ToggleFavoritesProfile($productId: Float!) {
	toggleFavoritesProfile(productId: $productId)
}

query GetUserFavoritesIdArray {
	getProfile {
		favorites {
			id
		}
	}
}